module.exports = function (s) {
  if (!s) return s
  var keys = { 
    EAN_UCC_13_SYMBOL: 'EAN_13',
    EAN_UCC_8_SYMBOL: 'EAN_8',
    ITF_14_SYMBOL: 'ITF_14',
    RSS_14: 'GS1_DATABAR_OMNIDIRECTIONAL',
    RSS_14_STACKED: 'GS1_DATABAR_STACKED',
    RSS_14_STACKED_OMNIDIRECTIONAL: 'GS1_DATABAR_STACKED_OMNIDIRECTIONAL',
    RSS_14_TRUNCATED: 'GS1_DATABAR_TRUNCATED',
    RSS_EXPANDED: 'GS1_DATABAR_EXPANDED',
    RSS_EXPANDED_STACKED: 'GS1_DATABAR_EXPANDED_STACKED',
    RSS_LIMITED: 'GS1_DATABAR_LIMITED',
    UCC_EAN_128_SYMBOL: 'GS1_128',
    UPC_A_SYMBOL: 'UPC_A',
    UPC_E_SYMBOL: 'UPC_E'
    ,UK: 'GTIN_14'
    ,UP: 'GTIN_12'
  }
  return keys[s] || s
}
