module.exports = function (s) {
  if (!s) return s
  var uom = { 
    "BQ": "BQL",
    "CAL": "E14",
    "BI": "BAR",
    "BR": "BLL",
    "BF": "BFT",
    "AF": "CGM",
    "C3": "CLT",
    "CM": "CMT",
    "CHD": "X_CHD",
    "C8": "DMQ",
    "CI": "INQ",
    "CR": "MTQ",
    "CO": "MTQ",
    "DA": "DAY",
    "CE": "CEL",
    "FA": "FAH",
    "DZ": "DZN",
    "FT": "FOT",
    "1N": "EA",
    "CC": "CMQ",
    "CF": "FTQ",
    "GR": "GRM",
    "GT": "E4",
    "DK": "KMT",
    "NGM": "X_NGM",
    "PPI": "X_PPI",
    "CW": "CWA",
    "IN": "INH",
    "KG": "KGM",
    "KVN": "X_KVN",
    "LT": "LTR",
    "MR": "MTR",
    "MP": "TNE",
    "MLM": "X_MLM",
    "ME": "MGM",
    "ML": "MLT",
    "MM": "MMT",
    "MTC": "X_MTC",
    "OZ": "ONZ",
    "PY": "G23",
    "PC": "H87",
    "PPC": "X_PPC",
    "LB": "LBR",
    "QS": "QTD",
    "QT": "QRT",
    "SPS": "X_SPS",
    "ST": "SET",
    "SF": "FTK",
    "SM": "MTK",
    "SY": "YDK",
    "15": "EA",
    "UN": "EA",
    "Z52": "E55",
    "YD": "YRD"
  }
  return uom[s] || s
}
